[workspace]
authors = ["Adolfo Ochagavía <github@adolfo.ochagavia.nl>"]
channels = ["conda-forge"]
name = "language-server-protocol"
platforms = [
    "linux-64",
    "linux-aarch64",
    "osx-arm64",
    "osx-64",
    "win-64",
]
version = "0.1.0"

[tasks]

[dependencies]
nodejs = "24.*"
pnpm = "10.*"
