import org.kson.GraalVmHelper

plugins {
    application
    kotlin("jvm")
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("com.github.ajalt.clikt:clikt:5.0.1")
    implementation(project(":kson-lib"))

    testImplementation(kotlin("test"))
    testImplementation(kotlin("test-junit"))
}

// Task to generate Version.kt with the kson-lib version
val generatedSrcDir = layout.buildDirectory.dir("generated/kotlin")
val generateVersion by tasks.registering {
    group = "build"
    description = "Generates Version.kt file with kson-lib version"

    val outputDir = generatedSrcDir.get().asFile.resolve("org/kson/tooling/cli/generated")
    val outputFile = outputDir.resolve("Version.kt")

    // Get version from kson-lib project
    val ksonLibVersion = project(":kson-lib").version.toString()

    outputs.file(outputFile)
    outputs.upToDateWhen { false } // Always regenerate to catch version changes

    doLast {
        outputDir.mkdirs()
        outputFile.writeText("""
            |// AUTO-GENERATED FILE - DO NOT EDIT
            |// Generated by generateVersion task in build.gradle.kts
            |package org.kson.tooling.cli.generated
            |
            |internal const val KSON_VERSION = "$ksonLibVersion"
        """.trimMargin())

        println("Generated Version.kt with KSON_VERSION = $ksonLibVersion")
    }
}

// Add generated sources to the main source set
kotlin {
    sourceSets {
        main {
            kotlin.srcDir(generatedSrcDir)
        }
    }
}

application {
    mainClass.set("org.kson.tooling.cli.CommandLineInterfaceKt")
}

// Custom task to build native image using GraalVM JDK
val buildNativeImage by tasks.registering(PixiExecTask::class) {
    group = "build"
    description = "Builds native executable using GraalVM from JDK toolchain"

    dependsOn(tasks.jar)

    val outputDir = layout.buildDirectory.dir("native/nativeCompile").get().asFile
    val outputFile = file("$outputDir/kson")

    // Configure the command at configuration time using providers
    command.set(provider {
        val graalHome = GraalVmHelper.getGraalVMHome()

        val nativeImageExe = file("${graalHome}/bin/native-image${GraalVmHelper.getNativeImageExtension()}")
        if (!nativeImageExe.exists()) {
            throw GradleException("native-image not found at $nativeImageExe. Ensure GraalVM JDK is properly installed.")
        }

        val classpath = configurations.runtimeClasspath.get().asPath
        val jarFile = tasks.jar.get().archiveFile.get().asFile

        listOf(
            nativeImageExe.absolutePath,
            "-cp", "${jarFile.absolutePath}${File.pathSeparator}$classpath",
            "-H:+ReportExceptionStackTraces",
            "--no-fallback",
            "-o", outputFile.absolutePath,
            "org.kson.tooling.cli.CommandLineInterfaceKt"
        )
    })

    doFirst {
        // Create output directory
        outputDir.mkdirs()

        println("Building native image with GraalVM using pixi")
        println("Creating executable: $outputFile")
    }

    doLast {
        if (outputFile.exists()) {
            println("\n✅ Native image built successfully!")
            println("   Executable: $outputFile")
            println("   Size: ${outputFile.length() / 1024 / 1024} MB")
            println("\nRun it with: $outputFile --help")
        }
    }
}

tasks{
    compileKotlin {
        dependsOn(generateVersion)
    }

    check {
        dependsOn(buildNativeImage)
    }
}
