[project]
name = "kson-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cffi>=1.17.1",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
