#!/usr/bin/env node

import {readFileSync, writeFileSync} from 'fs';
import {join, dirname} from 'path';
import {fileURLToPath} from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

interface LanguageConfig {
    id: string;
    aliases?: string[];
    scopeName: string;
    contentName: string;
}

/**
 * To add a new language, add it to this array.
 * The generator will automatically create the TextMate pattern
 */
const languages: LanguageConfig[] = [
    {
        id: 'typescript',
        aliases: ['ts'],
        scopeName: 'source.ts',
        contentName: 'meta.embedded.typescript'
    },
    {
        id: 'jinja',
        aliases: ['jinja'],
        scopeName: 'source.jinja',
        contentName: 'meta.embedded.jinja'
    },
    {
        id: 'javascript',
        aliases: ['js'],
        scopeName: 'source.js',
        contentName: 'meta.embedded.javascript'
    },
    {
        id: 'sql',
        scopeName: 'source.sql',
        contentName: 'meta.embedded.sql'
    },
    {
        id: 'python',
        aliases: ['py'],
        scopeName: 'source.python',
        contentName: 'meta.embedded.python'
    },
    {
        id: 'json',
        scopeName: 'source.json',
        contentName: 'meta.embedded.json'
    },
    {
        id: 'html',
        scopeName: 'text.html.basic',
        contentName: 'meta.embedded.html'
    },
    {
        id: 'css',
        scopeName: 'source.css',
        contentName: 'meta.embedded.css'
    },
    {
        id: 'java',
        scopeName: 'source.java',
        contentName: 'meta.embedded.java'
    },
    {
        id: 'cpp',
        aliases: ['c++', 'cxx'],
        scopeName: 'source.cpp',
        contentName: 'meta.embedded.cpp'
    },
    {
        id: 'csharp',
        aliases: ['cs', 'c#'],
        scopeName: 'source.cs',
        contentName: 'meta.embedded.csharp'
    },
    {
        id: 'go',
        scopeName: 'source.go',
        contentName: 'meta.embedded.go'
    },
    {
        id: 'rust',
        aliases: ['rs'],
        scopeName: 'source.rust',
        contentName: 'meta.embedded.rust'
    },
    {
        id: 'ruby',
        aliases: ['rb'],
        scopeName: 'source.ruby',
        contentName: 'meta.embedded.ruby'
    },
    {
        id: 'yaml',
        aliases: ['yml'],
        scopeName: 'source.yaml',
        contentName: 'meta.embedded.yaml'
    },
    {
        id: 'xml',
        scopeName: 'text.xml',
        contentName: 'meta.embedded.xml'
    },
    {
        id: 'markdown',
        aliases: ['md'],
        scopeName: 'text.html.markdown',
        contentName: 'meta.embedded.markdown'
    },
    {
        id: 'shell',
        aliases: ['sh', 'bash', 'zsh'],
        scopeName: 'source.shell',
        contentName: 'meta.embedded.shell'
    }
];

/**
 * Escape regex metacharacters so language ids and aliases are matched literally.
 * Without this, aliases like `c++` and `c#` are interpreted as regex syntax.
 */
const escapeRe = (s: string) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

/**
 * The characters that may open an embed block. A block opened by one of these closes at the first occurrence
 * of that same character doubled, so each gets its own generated pattern with its end-delimiter spelled out.
 */
const embedDelimiters = ['%', '$'];

/**
 * Generate the textmate grammar pattern for injecting a language in an embed block through the embed tag.
 *
 * @param delimiter - The character that opens the block, one of `embedDelimiters`.
 * @param lang - Optional language configuration. If not provided, generates a generic pattern.
 */
function generateEmbedPattern(delimiter: string, lang?: LanguageConfig) {
    const isGeneric = !lang;
    const delimiterPattern = escapeRe(delimiter);
    // The close delimiter is always the open delimiter doubled; see `EmbedDelim` in the core parser for why
    // escaping guarantees this naive search is always correct.
    const endDelimiterPattern = delimiterPattern + delimiterPattern;

    // Build the language pattern
    const langPattern = isGeneric
        ? '(.+)?'
        : `(${[lang.id, ...(lang.aliases ?? [])].map(escapeRe).join('|')})`;

    // Build the name
    const name = isGeneric
        ? 'meta.embedded.block.generic.kson'
        : `meta.embedded.block.${lang.id}.kson`;

    // Build the content name
    const contentName = isGeneric
        ? 'string.unquoted.embedded.kson'
        : lang.contentName;

    // Build the patterns array
    const noEndDelimiterOnLine = `(^|\\G)(?!.*${endDelimiterPattern})`;
    const patterns = isGeneric
        ? []
        : [{
            begin: noEndDelimiterOnLine,
            while: noEndDelimiterOnLine,
            patterns: [{include: lang.scopeName}]
        }];

    return {
        __comment: `IMPORTANT: Generated by ./scripts/generate-tm-enmbed-block.ts. Edit that file and re-run to update the TextMate grammar.`,
        name,
        // `[ \t\r]` is the lexer's inline whitespace; `\s` would also match the newline
        // that ends the tag.
        begin: `(${delimiterPattern})[ \\t\\r]*${langPattern}${isGeneric ? '' : '(?=[ \\t\\r]|$)'}.*?$`,
        beginCaptures: {
            "0": {
                name: "punctuation.section.embedded.begin.kson"
            },
            "1": {
                name: "punctuation.definition.embedded.kson"
            },
            "2": {
                name: "entity.name.tag.embedded.kson"
            }
        },
        end: endDelimiterPattern,
        endCaptures: {
            "0": {
                name: "punctuation.section.embedded.end.kson"
            }
        },
        contentName,
        patterns
    };
}

/**
 * Since generating the injection patterns is pretty wieldy and error-prone we generate and update that part of the
 * TextMate Grammar automatically.
 */
function generateTmEmbedBlock() {
    const tmLanguagePath = join(__dirname, '..', 'extension', 'config', 'kson.tmLanguage.json');
    const tmLanguage = JSON.parse(readFileSync(tmLanguagePath, 'utf-8'));

    // For each delimiter: every configured language, then the generic catch-all
    const embedPatterns = embedDelimiters.flatMap(delimiter => [
        ...languages.map(lang => generateEmbedPattern(delimiter, lang)),
        generateEmbedPattern(delimiter)
    ]);

    // Update the embed-blocks repository
    tmLanguage.repository['embed-blocks'] = {
        patterns: embedPatterns
    };

    // Write the updated file
    writeFileSync(tmLanguagePath, JSON.stringify(tmLanguage, null, 2));
    console.log(`Generated ${embedPatterns.length} embed patterns in ${tmLanguagePath}`);
}

// Run the generator
generateTmEmbedBlock();
